# Generated by Django 4.2 on 2023-04-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.AddField(
            model_name='persona',
            name='legajo',
            field=models.IntegerField(default=0),
        ),
    ]
